### ISSUE TITLE
Calorie Counter(Second Iteration)

### ISSUE THREAD

**Issue by massaroc** [vcu-cmsc355-f17/android-app-ccnd-2#2]
As a ... Healthy Eater
So that... I can keep track of my calorie intake
I want to... keep track of  foods I ate and their calories.

**Comment by trand4** [comment]
Given that I want to check my calorie count for each day of the week
When I click the week progress tab
then I will see all the calorie I consumed for each day

**Comment by trand4** [comment]
Given that I add the food I ate for a specific time of the day
When I click the add button
Then it will give me an option to type the food I ate and add how much calories it is

**Comment by trand4** [comment]
Given that I want to set the limit on how many calories I can consume
When I click the setting button
Then I will be able to set the amount of calories I can consume for each day
