### ISSUE TITLE
Set a weekly schedule

### ISSUE THREAD

**Issue by massaroc** [vcu-cmsc355-f17/android-app-ccnd-2#3]
As a ... Planner
--
So that... I can plan which day I workout
I want to... set up a weekly lifting schedule

**Comment by trand4** [comment]
As a ... Planner
--
So that... I can plan which day I workout
I want to... set up a weekly lifting schedule

**Comment by massaroc** [comment]
Given I am on the home screen
If I click on the schedule button
Then it will take me to the schedule screen

**Comment by massaroc** [comment]
Given I am on the schedule screen
If I click on the edit schedule button
Then it will allow me to change the workout options for each day of the week

**Comment by massaroc** [comment]
Given I am on the schedule screen
If I click on the delete schedule button
Then it will clear the current schedule
