### ISSUE TITLE
Set goals

### ISSUE THREAD

**Issue by massaroc** [vcu-cmsc355-f17/android-app-ccnd-2#4]
As a ... Powerlifter
So that... I can measure my progress
I want to... add specific lifting goals and update them when I meet them

**Comment by trand4** [comment]
Given that I want to check my calorie count for each day of the week
When I click the week progress tab
then I will see all the calorie I consumed for each day

**Comment by trand4** [comment]
Given that I add the food I ate for a specific time of the day
When I click the add button
Then it will give me an option to type the food I ate and add how much calories it is

**Comment by trand4** [comment]
Given that I want to set the limit on how many calories I can consume
When I click the setting button
Then I will be able to set the amount of calories I can consume for each day

**Comment by trand4** [comment]
Given that I reached my goal and I want to update it for a specific exercise
When I click the add button next to that specific exercise progress graph
Then it will allow me to update the goal

**Comment by trand4** [comment]
Given that I want to update the amount of weight I lift for a specific exercise
When I click the add button next to that specific exercise progress graph
Then it will allow me to update the current weight I lift

**Comment by trand4** [comment]
Given that I want to add more exercise goals
When I click the add button on the to
Then it will allow me to add an exercise and the goal for that exercise
