### ISSUE TITLE
Example Workout Routines

### ISSUE THREAD

**Issue by trand4** [vcu-cmsc355-f17/android-app-ccnd-2#5]
As a ... Gym Newbie
So that... I can follow a specific workout routine
I want to... Pick a routine that leads me through the exercises

**Comment by massaroc** [comment]
Given I am on the home screen
If I click on the example workout routines button
Then it will take me to the example workouts screen

**Comment by massaroc** [comment]
Given I am on the example workout screen
If I click on arms button
It will give me a list of arm workout routines

**Comment by massaroc** [comment]
Given I am on the example workout screen and clicked on the arms button
If I click on an arms workout routine
Then it will give me a list of the workouts in the routine
