### ISSUE TITLE
Create my own workout routines (First Iteration)

### ISSUE THREAD

**Issue by trand4** [vcu-cmsc355-f17/android-app-ccnd-2#7]
As a ... Gym Goer
So that... I can create specific workouts for myself
I want to... add my specific routines to the workout app.

![gym rat - storyboards](https://user-images.githubusercontent.com/19717019/30980611-a783652e-a44f-11e7-8952-1a373790ccd1.jpg)

**Comment by nrhwest** [comment]
Scenario #1 
Given that I am on the Home screen
When I click on Custom Workout to make one
Then the next page I see should be a list of muscles

**Comment by nrhwest** [comment]
Scenario #2 
Given that I am on the Choose Muscle page
When I click on Triceps
Then I should see a list of exercises for Triceps

**Comment by nrhwest** [comment]
Scenario #3
Given that I am on the exercises for Triceps page
When I click on an exercise
Then it should save the exercise as apart of the workout and allow me to choose another on the same screen

**Comment by nrhwest** [comment]
Scenario 4
Given that I am on the exercises for Triceps page with a workout with one or more saved exercises
When I click on the Back button
Then I should be back on the Choose Muscle page to pick another muscle to add to the workout or save the work
