### ISSUE TITLE
Track running distance

### ISSUE THREAD

**Issue by nrhwest** [vcu-cmsc355-f17/android-app-ccnd-2#8]
As a ... runner
So that... I can keep track on how far I ran
I want to… add a mile tracker

**Comment by wellscr3** [comment]
Scenario 1: Given I am on the home screen
When I click on Run Tracker,
Then I am brought to the Run Tracker screen

**Comment by wellscr3** [comment]
Scenario 2: Given I am on the Run Tracker screen
When I click Start Run,
Then the tracker measures the speed distance and pace of the run

**Comment by wellscr3** [comment]
Scenario 3:  Given I am currently on a run in the Run Tracker
When I click stop Run
Then I am brought back to the Run Tracker screen, and my Run is saved under Previous Runs

**Comment by wellscr3** [comment]
Scenario 4: Given I am on the Run Tracker screen 
When I click previous runs
Then a list of previous runs appears

**Comment by wellscr3** [comment]
![runtracker](https://user-images.githubusercontent.com/31899341/30984531-96138c9a-a45b-11e7-90cf-f9d928d43824.jpg)
